### PR TITLE
Increase the number of max arguments to int.max

### PR DESCRIPTION
**Pull request by genuinelucifer**

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
I don't see why this is necessary. This is changing the default value. It's possible to change the value for a given instance without changing the default value.

**Comment by genuinelucifer** [comment]
> It's possible to change the value for a given instance without changing the default value.

In dstep, I have access to ```arguments``` from ```Arguments``` class.
And I don't think currently it is possible to change max arguments from the Arguments class object!
How do I do that?

**Comment by jacob-carlborg** [comment]
`Application` in DStack defines `arguments` which returns `Arguments` defined in mambo. `Arguments` defines `argument` which returns `Argument!(T)`, which inherits from `ArgumentBase` where `min` and `max` are defined.

**Comment by genuinelucifer** [comment]
Closing this as it is not the right way to go around things...

**Pull request closed without merging**
